blank_issues_enabled: false
contact_links:
  - name: Website help / questions
    url: https://github.com/serbianorthodox/serbianorthodox.github.io/discussions
    about: Ask questions or request support here.
